version: "3.5"
services:
  control-node:
    restart: "no"
    build:
      context: ../..
      dockerfile: docker/node/Dockerfile
    ports:
      # gRPC
      - 50051:50051
    links:
      - mpi-node-1
      - mpi-node-2
    environment:
      - USER_PROB_URL=https://resaas-public-data.s3.eu-central-1.amazonaws.com/probability.zip
    volumes:
      # Note: only the control node needs private key to spawn mpi processes
      # on other nodes via ssh.
      - $HOME/.ssh/dorran-resaas-pair.pem:/root/.ssh/id.pem
      - $HOME/.ssh/dorran-resaas-pair.pub:/app/config/ssh/authorized_keys
      - $HOME/Desktop/resaas:/resaas
      - local_storage_backend:/storage
    command:
      - resaas-controller
      - --job
      - testing
      - --storage
      - /resaas/storage.yaml
      - --hostsfile
      - /resaas/hostsfile
      - --job-spec
      - /resaas/job.json
      - --config
      - /resaas/controller.yaml
    depends_on: [mpi-node-1, mpi-node-2]

  mpi-node-1:
    build:
      context: ../..
      dockerfile: docker/node/Dockerfile
    environment:
      - USER_PROB_URL=https://resaas-public-data.s3.eu-central-1.amazonaws.com/probability.zip
    ports:
      - "26"
    volumes:
      - $HOME/.ssh/dorran-resaas-pair.pub:/app/config/ssh/authorized_keys
      - $HOME/Desktop/resaas:/resaas
      - local_storage_backend:/storage
    command:
      - /usr/sbin/sshd
      - -D
    depends_on: [graphite]
  mpi-node-2:
    ports:
      - "26"
    build:
      context: ../..
      dockerfile: docker/node/Dockerfile
    environment:
      - USER_PROB_URL=https://resaas-public-data.s3.eu-central-1.amazonaws.com/probability.zip
    volumes:
      - $HOME/.ssh/dorran-resaas-pair.pub:/app/config/ssh/authorized_keys
      - $HOME/Desktop/resaas:/resaas
      - local_storage_backend:/storage
    command:
      - /usr/sbin/sshd
      - -D
    depends_on: [graphite]

  graphite:
    image: "graphiteapp/graphite-statsd"
    restart: "always"
    ports:
      - "80:8080"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"

volumes:
  local_storage_backend:
