# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import status_checker_pb2 as status__checker__pb2


class StatusCheckerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthChecker = channel.unary_stream(
                '/StatusChecker/HealthChecker',
                request_serializer=status__checker__pb2.HealthStateRequest.SerializeToString,
                response_deserializer=status__checker__pb2.HealthStateResponse.FromString,
                )


class StatusCheckerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HealthChecker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatusCheckerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthChecker': grpc.unary_stream_rpc_method_handler(
                    servicer.HealthChecker,
                    request_deserializer=status__checker__pb2.HealthStateRequest.FromString,
                    response_serializer=status__checker__pb2.HealthStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'StatusChecker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StatusChecker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HealthChecker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/StatusChecker/HealthChecker',
            status__checker__pb2.HealthStateRequest.SerializeToString,
            status__checker__pb2.HealthStateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
