# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: status_checker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='status_checker.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14status_checker.proto\"\x14\n\x12HealthStateRequest\",\n\x13HealthStateResponse\x12\x15\n\rhealth_status\x18\x01 \x01(\t2O\n\rStatusChecker\x12>\n\rHealthChecker\x12\x13.HealthStateRequest\x1a\x14.HealthStateResponse\"\x00\x30\x01\x62\x06proto3'
)




_HEALTHSTATEREQUEST = _descriptor.Descriptor(
  name='HealthStateRequest',
  full_name='HealthStateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=44,
)


_HEALTHSTATERESPONSE = _descriptor.Descriptor(
  name='HealthStateResponse',
  full_name='HealthStateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='health_status', full_name='HealthStateResponse.health_status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['HealthStateRequest'] = _HEALTHSTATEREQUEST
DESCRIPTOR.message_types_by_name['HealthStateResponse'] = _HEALTHSTATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HealthStateRequest = _reflection.GeneratedProtocolMessageType('HealthStateRequest', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHSTATEREQUEST,
  '__module__' : 'status_checker_pb2'
  # @@protoc_insertion_point(class_scope:HealthStateRequest)
  })
_sym_db.RegisterMessage(HealthStateRequest)

HealthStateResponse = _reflection.GeneratedProtocolMessageType('HealthStateResponse', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHSTATERESPONSE,
  '__module__' : 'status_checker_pb2'
  # @@protoc_insertion_point(class_scope:HealthStateResponse)
  })
_sym_db.RegisterMessage(HealthStateResponse)



_STATUSCHECKER = _descriptor.ServiceDescriptor(
  name='StatusChecker',
  full_name='StatusChecker',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=92,
  serialized_end=171,
  methods=[
  _descriptor.MethodDescriptor(
    name='HealthChecker',
    full_name='StatusChecker.HealthChecker',
    index=0,
    containing_service=None,
    input_type=_HEALTHSTATEREQUEST,
    output_type=_HEALTHSTATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STATUSCHECKER)

DESCRIPTOR.services_by_name['StatusChecker'] = _STATUSCHECKER

# @@protoc_insertion_point(module_scope)
