# docker run -v  -v $PWD/osu_latency.py:/osu_latency.py  59c6e26c1f27 /app/deps/openmpi/bin/mpirun --allow-run-as-root /app/deps/rexfw/bin/python /osu_latency.py
version: "3.5"
services:
  mpi-master:
    build:
      context: .
      dockerfile: docker/node/base/Dockerfile
    # image: openmpi
    ports:
      - "22"
    links:
      - mpi-node-1
      - mpi-node-2
    volumes:
      - $HOME/.ssh/dorran-resaas-pair.pem:/root/.ssh/id.pem
      - $HOME/.ssh/dorran-resaas-pair.pub:/app/config/ssh/authorized_keys
      - $HOME/Desktop/resaas:/resaas
    command:
      - resaas-controller
      - --job
      - testing
      - --storage
      - /resaas/storage.yaml
      - --hostsfile
      - /resaas/hostsfile
      - --job-spec
      - /resaas/job.json
      - --config
      - /resaas/controller.yaml
    depends_on: [mpi-node-1, mpi-node-2]

  mpi-node-1:
    build:
      context: .
      dockerfile: docker/node/base/Dockerfile
    ports:
      - "26"
    volumes:
      - $HOME/.ssh/dorran-resaas-pair.pub:/app/config/ssh/authorized_keys
      - $HOME/resaas:/resaas
    command:
      - /usr/sbin/sshd
      - -D

  mpi-node-2:
    ports:
      - "26"
    build:
      context: .
      dockerfile: docker/node/base/Dockerfile
    volumes:
      - $HOME/.ssh/dorran-resaas-pair.pub:/app/config/ssh/authorized_keys
      - $HOME/resaas:/resaas
    command:
      - /usr/sbin/sshd
      - -D
