controller:
  image: TODO
  cmd: chainsail-controller
  args:
    - --job
    - "{job_id}"
    - --storage
    - /chainsail/storage.yaml
    - --hostsfile
    - /chainsail/hostfile
    - --job-spec
    - /chainsail/job.json
    - --config
    - /chainsail/controller.yaml
  ports: [50051, 26]
  user_code_image: TODO

worker:
  image: TODO
  cmd: /usr/sbin/sshd
  args:
    - -D
  ports: [26]
  user_code_image: TODO

# signed URLs the user requests are valid for n seconds
# (here: 604800 seconds = 1 week)
results_url_expiry_time: 604800

node_type: LibcloudVM

remote_logging_config_path: TODO

node_config:
  # Custom resaas-dev-node image
  vm_image_id: "8373025462420862349"
  vm_size: "e2-standard-2"
  # User is same as one defined in instance metadata below
  ssh_user: ubuntu
  ssh_public_key: "ssh-rsa ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCxrjgZC7qz7Ern5I2S80u1kN+GY2y+WShfcJ/ZLjFH0MHRrK1pOtzz1BoCxje+sMTzOb/rXyxDUe2jGmBvVcifelO2MblXOBlCBRwwuACv3ChqOfu3Kjgpgn12am3hxyp1xAScbFlzG5/bF6ggx0T4QxBcJVwa1gwnVjaZnXikg36amMAMpUScN2Irl8XLPJgvM+jyV69YxsENuUszLKcuVKbgoWC6NBArbD2l3mUGOrmdGuF8vBts4VrwcpEmvAufwrtg+pz5Bsh5XqVYi+WVcXp83JhHMJHFN2QoNLUNf8qBU7gdFRG/ISa3AGICjOiOC+SE8CRgsiOwkXqvaCoeNAuIWNRP57rzezW9B09CfgsKUN9OafDz+pFdaDoM1a2Qa997YuXbxLvVnoSY81nd+thC+ugm3rHLvx+8VG65aP0Og2h0LcGkTCHGqYi6/3o2wcie5yGuxiRAU4jeQrz4JhgBLw6N/e2xvdtuq+bcp0QLPVxvMLvZN/MS09iY9fU= unsafeDevKey"
  ssh_private_key_path: /config/unsafe_private_key.pem
  storage_config_path: /config/storage.yaml
  controller_config_path: /config/controller.yaml

  libcloud_provider: GCE

  libcloud_driver_inputs:
    user_id: resaas-gce@resaas-simeon-dev.iam.gserviceaccount.com
    key: /config/gce_key.json
    project: resaas-simeon-dev
    auth_type: SA
    datacenter: europe-west1-b

  libcloud_create_node_inputs:
    # ex_network: resaas
    ex_boot_disk:
    # Required to enable ssh login
    ex_metadata:
      items:
        - {
            "key": "ssh-keys",
            "value": "ubuntu: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCxrjgZC7qz7Ern5I2S80u1kN+GY2y+WShfcJ/ZLjFH0MHRrK1pOtzz1BoCxje+sMTzOb/rXyxDUe2jGmBvVcifelO2MblXOBlCBRwwuACv3ChqOfu3Kjgpgn12am3hxyp1xAScbFlzG5/bF6ggx0T4QxBcJVwa1gwnVjaZnXikg36amMAMpUScN2Irl8XLPJgvM+jyV69YxsENuUszLKcuVKbgoWC6NBArbD2l3mUGOrmdGuF8vBts4VrwcpEmvAufwrtg+pz5Bsh5XqVYi+WVcXp83JhHMJHFN2QoNLUNf8qBU7gdFRG/ISa3AGICjOiOC+SE8CRgsiOwkXqvaCoeNAuIWNRP57rzezW9B09CfgsKUN9OafDz+pFdaDoM1a2Qa997YuXbxLvVnoSY81nd+thC+ugm3rHLvx+8VG65aP0Og2h0LcGkTCHGqYi6/3o2wcie5yGuxiRAU4jeQrz4JhgBLw6N/e2xvdtuq+bcp0QLPVxvMLvZN/MS09iY9fU= unsafeDevKey",
          }
    ex_service_accounts:
      - { "email": "default", "scopes": ["cloud-platform"] }

  init_script: |
    # Initialize the docker credentials helper
    docker-credential-gcr configure-docker
