controller:
  image: eu.gcr.io/cloud-platform-learning-dh/resaas-controller:dev17
  cmd: resaas-controller
  args:
    - --job
    - "{job_id}"
    - --storage
    - /resaas/storage.yaml
    - --hostsfile
    - /resaas/hostfile
    - --job-spec
    - /resaas/job.json
    - --config
    - /resaas/controller.yaml
  ports: [50051, 26]

worker:
  image: eu.gcr.io/cloud-platform-learning-dh/resaas-controller:dev17
  cmd: /usr/sbin/sshd
  args:
    - -D
  ports: [26]

node_type: LibcloudVM

node_config:
  # Custom resaas-dev-node image
  vm_image_id: "6581594611843370864"
  vm_size: "e2-standard-2"
  # User is same as one defined in instance metadata below
  ssh_user: ubuntu
  ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCnEsQk2O0MLZpk3zGOXfdxkmPW9T68lLm74qHU1y/b1Cir6cmRBUMCX3mSrLrqtwUEHvOfmj4QT8fVpwF1JamRGUUNFwa8+Re/dCKwh6qwUaH2c0b4oVyggqNPvZbC7+o/TA0XpVT+isFXiW5Z1wBLWvO6RlCzsjCdl8k+L45BtvgNVE2TROaXDtnizL4Bs6lwG0a3h/6q/ck4S9QOvWLxQrah3o6hrXUf5Wd9S8oquwN5bHdwPes84+mKr2wXFiToZJMVUN8X0pdIZd1DnF1nDr4FDlKgn0/lUjOozcyyVU7L3sl3kKslx3ZmMPowdNTcn9xIEtASHL05kJkSvDcD resaasDevKeyDorran"
  ssh_private_key_path: /home/dorran/dorran-resaas-pair.pem
  storage_config_path: /home/dorran/resaas/storage.yaml
  controller_config_path: /home/dorran/resaas/controller.yaml

  libcloud_provider: GCE

  libcloud_driver_inputs:
    user_id: resaas-dev@cloud-platform-learning-dh.iam.gserviceaccount.com
    key: /home/dorran/cloud-platform-learning-dh-bf48dce76d1b.json
    project: cloud-platform-learning-dh
    auth_type: SA
    datacenter: europe-west1-b

  libcloud_create_node_inputs:
    # ex_network: resaas
    ex_boot_disk:
    # Required to enable ssh login
    ex_metadata:
      items:
        - {
            "key": "ssh-keys",
            "value": "ubuntu: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCnEsQk2O0MLZpk3zGOXfdxkmPW9T68lLm74qHU1y/b1Cir6cmRBUMCX3mSrLrqtwUEHvOfmj4QT8fVpwF1JamRGUUNFwa8+Re/dCKwh6qwUaH2c0b4oVyggqNPvZbC7+o/TA0XpVT+isFXiW5Z1wBLWvO6RlCzsjCdl8k+L45BtvgNVE2TROaXDtnizL4Bs6lwG0a3h/6q/ck4S9QOvWLxQrah3o6hrXUf5Wd9S8oquwN5bHdwPes84+mKr2wXFiToZJMVUN8X0pdIZd1DnF1nDr4FDlKgn0/lUjOozcyyVU7L3sl3kKslx3ZmMPowdNTcn9xIEtASHL05kJkSvDcD resaasDevKeyDorran",
          }
    ex_service_accounts:
      - { "email": "default", "scopes": ["cloud-platform"] }

  init_script: |
    # Initialize the docker credentials helper
    docker-credential-gcr configure-docker
