env: standard
runtime: nodejs12
service: default

env_variables:
  # these are GCP-internal IPs + port, such as 10.156.0.3:80
  GRAPHITE_URL: TODO
  SCHEDULER_URL: TODO

vpc_access_connector:
  # this is the VPC connector resource (connectors are listed or have to be added here:
  # https://console.cloud.google.com/networking/connectors/list?project=resaas-simeon-dev)
  # The format is projects/<numerical project id>/locations/<location>/connectors/<connector name>
  name: TODO

handlers:
  - url: /.*
    secure: always
    script: auto
