ssh_user: ubuntu
ssh_public_key: "ssh-rsa XXXXXXXXXXXXXXXXXXXXXXXX yourComment"
ssh_private_key_path: /home/user/.ssh/your-resaas-key.pem
node_entrypoint: bash -c 'echo gruezi'
node_ports: [8080]
node_image: ami-0502e817a62226e03 # "ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20201026"
node_size: "t2.micro"
node_type: LibcloudVM
node_driver: "ec2"
driver_specs:
  dummy:
    creds: "forTestingOnly"
    extra_creation_kwargs: {}
  ec2:
    key: XXXXXXXXXXXXXXXXXX
    secret: XXXXXXXXXXXXXXXXXXXXXXXXX
    token: >-
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    region: "eu-central-1"
    extra_creation_kwargs:
      ex_security_groups: ["default", "resaas"]
