# Kubeconfig file
# It specifies the kubernetes cluster credentials.
# Fill-in the placeholders for your cluster.
# Instructions are detailed here: ../docs/deployment.md
apiVersion: v1
kind: Config
clusters:
- name: <cluster-name>
  cluster:
    server: https://<endpoint>
    certificate-authority-data: <masterAuth.clusterCaCertificate>
users:
- name: chainsail-scheduler
  user:
    auth-provider:
      name: gcp
contexts:
- context:
    cluster: <cluster-name>
    user: chainsail-scheduler
  name: <cluster-name>
current-context: <cluster-name>
