version: "3.5"

services:
  # Scheduler database
  postgres:
    image: postgres:11.5-alpine
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      # Using default "postgres" database and "postgres" user
      - POSTGRES_PASSWORD=chainsail-dev
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  pgadmin:
    image: dpage/pgadmin4:5.4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    volumes:
      - ./pg-servers.json:/pgadmin4/servers.json
    ports:
      - "81:80"
    depends_on:
      - postgres
  # For async-task message passing
  redis:
    image: redis:6.2-rc2-alpine
    volumes:
      - redis:/data
    ports:
      - 6379:6379
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  graphite:
    image: "graphiteapp/graphite-statsd@sha256:f611a3b4c9b176957a95abdc419366da35bd92d228d3935fc7ae3a5247be5307"
    restart: "always"
    ports:
      - "8080:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    volumes:
      - ./graphite-storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
volumes:
  redis:
  postgres:
