# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user-code.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0fuser-code.proto"5\n\x0eLogProbRequest\x12\x13\n\x0bstate_bytes\x18\x01 \x01(\x0c\x12\x0e\n\x06job_id\x18\x02 \x01(\x05"*\n\x0fLogProbResponse\x12\x17\n\x0flog_prob_result\x18\x01 \x01(\x02"=\n\x16LogProbGradientRequest\x12\x13\n\x0bstate_bytes\x18\x01 \x01(\x0c\x12\x0e\n\x06job_id\x18\x02 \x01(\x05"1\n\x17LogProbGradientResponse\x12\x16\n\x0egradient_bytes\x18\x01 \x01(\x0c";\n\x14LogLikelihoodRequest\x12\x13\n\x0bstate_bytes\x18\x01 \x01(\x0c\x12\x0e\n\x06job_id\x18\x02 \x01(\x05"6\n\x15LogLikelihoodResponse\x12\x1d\n\x15log_likelihood_result\x18\x01 \x01(\x02"C\n\x1cLogLikelihoodGradientRequest\x12\x13\n\x0bstate_bytes\x18\x01 \x01(\x0c\x12\x0e\n\x06job_id\x18\x02 \x01(\x05"7\n\x1dLogLikelihoodGradientResponse\x12\x16\n\x0egradient_bytes\x18\x01 \x01(\x0c"6\n\x0fLogPriorRequest\x12\x13\n\x0bstate_bytes\x18\x01 \x01(\x0c\x12\x0e\n\x06job_id\x18\x02 \x01(\x05",\n\x10LogPriorResponse\x12\x18\n\x10log_prior_result\x18\x01 \x01(\x02">\n\x17LogPriorGradientRequest\x12\x13\n\x0bstate_bytes\x18\x01 \x01(\x0c\x12\x0e\n\x06job_id\x18\x02 \x01(\x05"2\n\x18LogPriorGradientResponse\x12\x16\n\x0egradient_bytes\x18\x01 \x01(\x0c"%\n\x13InitialStateRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\x05"3\n\x14InitialStateResponse\x12\x1b\n\x13initial_state_bytes\x18\x01 \x01(\x0c\x32\xcd\x03\n\x08UserCode\x12,\n\x07LogProb\x12\x0f.LogProbRequest\x1a\x10.LogProbResponse\x12\x44\n\x0fLogProbGradient\x12\x17.LogProbGradientRequest\x1a\x18.LogProbGradientResponse\x12>\n\rLogLikelihood\x12\x15.LogLikelihoodRequest\x1a\x16.LogLikelihoodResponse\x12V\n\x15LogLikelihoodGradient\x12\x1d.LogLikelihoodGradientRequest\x1a\x1e.LogLikelihoodGradientResponse\x12/\n\x08LogPrior\x12\x10.LogPriorRequest\x1a\x11.LogPriorResponse\x12G\n\x10LogPriorGradient\x12\x18.LogPriorGradientRequest\x1a\x19.LogPriorGradientResponse\x12;\n\x0cInitialState\x12\x14.InitialStateRequest\x1a\x15.InitialStateResponseb\x06proto3'
)


_LOGPROBREQUEST = DESCRIPTOR.message_types_by_name["LogProbRequest"]
_LOGPROBRESPONSE = DESCRIPTOR.message_types_by_name["LogProbResponse"]
_LOGPROBGRADIENTREQUEST = DESCRIPTOR.message_types_by_name["LogProbGradientRequest"]
_LOGPROBGRADIENTRESPONSE = DESCRIPTOR.message_types_by_name["LogProbGradientResponse"]
_LOGLIKELIHOODREQUEST = DESCRIPTOR.message_types_by_name["LogLikelihoodRequest"]
_LOGLIKELIHOODRESPONSE = DESCRIPTOR.message_types_by_name["LogLikelihoodResponse"]
_LOGLIKELIHOODGRADIENTREQUEST = DESCRIPTOR.message_types_by_name["LogLikelihoodGradientRequest"]
_LOGLIKELIHOODGRADIENTRESPONSE = DESCRIPTOR.message_types_by_name["LogLikelihoodGradientResponse"]
_LOGPRIORREQUEST = DESCRIPTOR.message_types_by_name["LogPriorRequest"]
_LOGPRIORRESPONSE = DESCRIPTOR.message_types_by_name["LogPriorResponse"]
_LOGPRIORGRADIENTREQUEST = DESCRIPTOR.message_types_by_name["LogPriorGradientRequest"]
_LOGPRIORGRADIENTRESPONSE = DESCRIPTOR.message_types_by_name["LogPriorGradientResponse"]
_INITIALSTATEREQUEST = DESCRIPTOR.message_types_by_name["InitialStateRequest"]
_INITIALSTATERESPONSE = DESCRIPTOR.message_types_by_name["InitialStateResponse"]
LogProbRequest = _reflection.GeneratedProtocolMessageType(
    "LogProbRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _LOGPROBREQUEST,
        "__module__": "user_code_pb2"
        # @@protoc_insertion_point(class_scope:LogProbRequest)
    },
)
_sym_db.RegisterMessage(LogProbRequest)

LogProbResponse = _reflection.GeneratedProtocolMessageType(
    "LogProbResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _LOGPROBRESPONSE,
        "__module__": "user_code_pb2"
        # @@protoc_insertion_point(class_scope:LogProbResponse)
    },
)
_sym_db.RegisterMessage(LogProbResponse)

LogProbGradientRequest = _reflection.GeneratedProtocolMessageType(
    "LogProbGradientRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _LOGPROBGRADIENTREQUEST,
        "__module__": "user_code_pb2"
        # @@protoc_insertion_point(class_scope:LogProbGradientRequest)
    },
)
_sym_db.RegisterMessage(LogProbGradientRequest)

LogProbGradientResponse = _reflection.GeneratedProtocolMessageType(
    "LogProbGradientResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _LOGPROBGRADIENTRESPONSE,
        "__module__": "user_code_pb2"
        # @@protoc_insertion_point(class_scope:LogProbGradientResponse)
    },
)
_sym_db.RegisterMessage(LogProbGradientResponse)

LogLikelihoodRequest = _reflection.GeneratedProtocolMessageType(
    "LogLikelihoodRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _LOGLIKELIHOODREQUEST,
        "__module__": "user_code_pb2"
        # @@protoc_insertion_point(class_scope:LogLikelihoodRequest)
    },
)
_sym_db.RegisterMessage(LogLikelihoodRequest)

LogLikelihoodResponse = _reflection.GeneratedProtocolMessageType(
    "LogLikelihoodResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _LOGLIKELIHOODRESPONSE,
        "__module__": "user_code_pb2"
        # @@protoc_insertion_point(class_scope:LogLikelihoodResponse)
    },
)
_sym_db.RegisterMessage(LogLikelihoodResponse)

LogLikelihoodGradientRequest = _reflection.GeneratedProtocolMessageType(
    "LogLikelihoodGradientRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _LOGLIKELIHOODGRADIENTREQUEST,
        "__module__": "user_code_pb2"
        # @@protoc_insertion_point(class_scope:LogLikelihoodGradientRequest)
    },
)
_sym_db.RegisterMessage(LogLikelihoodGradientRequest)

LogLikelihoodGradientResponse = _reflection.GeneratedProtocolMessageType(
    "LogLikelihoodGradientResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _LOGLIKELIHOODGRADIENTRESPONSE,
        "__module__": "user_code_pb2"
        # @@protoc_insertion_point(class_scope:LogLikelihoodGradientResponse)
    },
)
_sym_db.RegisterMessage(LogLikelihoodGradientResponse)

LogPriorRequest = _reflection.GeneratedProtocolMessageType(
    "LogPriorRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _LOGPRIORREQUEST,
        "__module__": "user_code_pb2"
        # @@protoc_insertion_point(class_scope:LogPriorRequest)
    },
)
_sym_db.RegisterMessage(LogPriorRequest)

LogPriorResponse = _reflection.GeneratedProtocolMessageType(
    "LogPriorResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _LOGPRIORRESPONSE,
        "__module__": "user_code_pb2"
        # @@protoc_insertion_point(class_scope:LogPriorResponse)
    },
)
_sym_db.RegisterMessage(LogPriorResponse)

LogPriorGradientRequest = _reflection.GeneratedProtocolMessageType(
    "LogPriorGradientRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _LOGPRIORGRADIENTREQUEST,
        "__module__": "user_code_pb2"
        # @@protoc_insertion_point(class_scope:LogPriorGradientRequest)
    },
)
_sym_db.RegisterMessage(LogPriorGradientRequest)

LogPriorGradientResponse = _reflection.GeneratedProtocolMessageType(
    "LogPriorGradientResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _LOGPRIORGRADIENTRESPONSE,
        "__module__": "user_code_pb2"
        # @@protoc_insertion_point(class_scope:LogPriorGradientResponse)
    },
)
_sym_db.RegisterMessage(LogPriorGradientResponse)

InitialStateRequest = _reflection.GeneratedProtocolMessageType(
    "InitialStateRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _INITIALSTATEREQUEST,
        "__module__": "user_code_pb2"
        # @@protoc_insertion_point(class_scope:InitialStateRequest)
    },
)
_sym_db.RegisterMessage(InitialStateRequest)

InitialStateResponse = _reflection.GeneratedProtocolMessageType(
    "InitialStateResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _INITIALSTATERESPONSE,
        "__module__": "user_code_pb2"
        # @@protoc_insertion_point(class_scope:InitialStateResponse)
    },
)
_sym_db.RegisterMessage(InitialStateResponse)

_USERCODE = DESCRIPTOR.services_by_name["UserCode"]
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _LOGPROBREQUEST._serialized_start = 19
    _LOGPROBREQUEST._serialized_end = 72
    _LOGPROBRESPONSE._serialized_start = 74
    _LOGPROBRESPONSE._serialized_end = 116
    _LOGPROBGRADIENTREQUEST._serialized_start = 118
    _LOGPROBGRADIENTREQUEST._serialized_end = 179
    _LOGPROBGRADIENTRESPONSE._serialized_start = 181
    _LOGPROBGRADIENTRESPONSE._serialized_end = 230
    _LOGLIKELIHOODREQUEST._serialized_start = 232
    _LOGLIKELIHOODREQUEST._serialized_end = 291
    _LOGLIKELIHOODRESPONSE._serialized_start = 293
    _LOGLIKELIHOODRESPONSE._serialized_end = 347
    _LOGLIKELIHOODGRADIENTREQUEST._serialized_start = 349
    _LOGLIKELIHOODGRADIENTREQUEST._serialized_end = 416
    _LOGLIKELIHOODGRADIENTRESPONSE._serialized_start = 418
    _LOGLIKELIHOODGRADIENTRESPONSE._serialized_end = 473
    _LOGPRIORREQUEST._serialized_start = 475
    _LOGPRIORREQUEST._serialized_end = 529
    _LOGPRIORRESPONSE._serialized_start = 531
    _LOGPRIORRESPONSE._serialized_end = 575
    _LOGPRIORGRADIENTREQUEST._serialized_start = 577
    _LOGPRIORGRADIENTREQUEST._serialized_end = 639
    _LOGPRIORGRADIENTRESPONSE._serialized_start = 641
    _LOGPRIORGRADIENTRESPONSE._serialized_end = 691
    _INITIALSTATEREQUEST._serialized_start = 693
    _INITIALSTATEREQUEST._serialized_end = 730
    _INITIALSTATERESPONSE._serialized_start = 732
    _INITIALSTATERESPONSE._serialized_end = 783
    _USERCODE._serialized_start = 786
    _USERCODE._serialized_end = 1247
# @@protoc_insertion_point(module_scope)
