# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chainsail.grpc.user_code_pb2 as user__code__pb2


class UserCodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LogProb = channel.unary_unary(
                '/grpc.health.v1.UserCode/LogProb',
                request_serializer=user__code__pb2.LogProbRequest.SerializeToString,
                response_deserializer=user__code__pb2.LogProbResponse.FromString,
                )
        self.LogProbGradient = channel.unary_unary(
                '/grpc.health.v1.UserCode/LogProbGradient',
                request_serializer=user__code__pb2.LogProbGradientRequest.SerializeToString,
                response_deserializer=user__code__pb2.LogProbGradientResponse.FromString,
                )
        self.LogLikelihood = channel.unary_unary(
                '/grpc.health.v1.UserCode/LogLikelihood',
                request_serializer=user__code__pb2.LogLikelihoodRequest.SerializeToString,
                response_deserializer=user__code__pb2.LogLikelihoodResponse.FromString,
                )
        self.LogLikelihoodGradient = channel.unary_unary(
                '/grpc.health.v1.UserCode/LogLikelihoodGradient',
                request_serializer=user__code__pb2.LogLikelihoodGradientRequest.SerializeToString,
                response_deserializer=user__code__pb2.LogLikelihoodGradientResponse.FromString,
                )
        self.LogPrior = channel.unary_unary(
                '/grpc.health.v1.UserCode/LogPrior',
                request_serializer=user__code__pb2.LogPriorRequest.SerializeToString,
                response_deserializer=user__code__pb2.LogPriorResponse.FromString,
                )
        self.LogPriorGradient = channel.unary_unary(
                '/grpc.health.v1.UserCode/LogPriorGradient',
                request_serializer=user__code__pb2.LogPriorGradientRequest.SerializeToString,
                response_deserializer=user__code__pb2.LogPriorGradientResponse.FromString,
                )
        self.InitialState = channel.unary_unary(
                '/grpc.health.v1.UserCode/InitialState',
                request_serializer=user__code__pb2.InitialStateRequest.SerializeToString,
                response_deserializer=user__code__pb2.InitialStateResponse.FromString,
                )


class UserCodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LogProb(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogProbGradient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogLikelihood(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogLikelihoodGradient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogPrior(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogPriorGradient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitialState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserCodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LogProb': grpc.unary_unary_rpc_method_handler(
                    servicer.LogProb,
                    request_deserializer=user__code__pb2.LogProbRequest.FromString,
                    response_serializer=user__code__pb2.LogProbResponse.SerializeToString,
            ),
            'LogProbGradient': grpc.unary_unary_rpc_method_handler(
                    servicer.LogProbGradient,
                    request_deserializer=user__code__pb2.LogProbGradientRequest.FromString,
                    response_serializer=user__code__pb2.LogProbGradientResponse.SerializeToString,
            ),
            'LogLikelihood': grpc.unary_unary_rpc_method_handler(
                    servicer.LogLikelihood,
                    request_deserializer=user__code__pb2.LogLikelihoodRequest.FromString,
                    response_serializer=user__code__pb2.LogLikelihoodResponse.SerializeToString,
            ),
            'LogLikelihoodGradient': grpc.unary_unary_rpc_method_handler(
                    servicer.LogLikelihoodGradient,
                    request_deserializer=user__code__pb2.LogLikelihoodGradientRequest.FromString,
                    response_serializer=user__code__pb2.LogLikelihoodGradientResponse.SerializeToString,
            ),
            'LogPrior': grpc.unary_unary_rpc_method_handler(
                    servicer.LogPrior,
                    request_deserializer=user__code__pb2.LogPriorRequest.FromString,
                    response_serializer=user__code__pb2.LogPriorResponse.SerializeToString,
            ),
            'LogPriorGradient': grpc.unary_unary_rpc_method_handler(
                    servicer.LogPriorGradient,
                    request_deserializer=user__code__pb2.LogPriorGradientRequest.FromString,
                    response_serializer=user__code__pb2.LogPriorGradientResponse.SerializeToString,
            ),
            'InitialState': grpc.unary_unary_rpc_method_handler(
                    servicer.InitialState,
                    request_deserializer=user__code__pb2.InitialStateRequest.FromString,
                    response_serializer=user__code__pb2.InitialStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.health.v1.UserCode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserCode(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LogProb(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.health.v1.UserCode/LogProb',
            user__code__pb2.LogProbRequest.SerializeToString,
            user__code__pb2.LogProbResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LogProbGradient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.health.v1.UserCode/LogProbGradient',
            user__code__pb2.LogProbGradientRequest.SerializeToString,
            user__code__pb2.LogProbGradientResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LogLikelihood(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.health.v1.UserCode/LogLikelihood',
            user__code__pb2.LogLikelihoodRequest.SerializeToString,
            user__code__pb2.LogLikelihoodResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LogLikelihoodGradient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.health.v1.UserCode/LogLikelihoodGradient',
            user__code__pb2.LogLikelihoodGradientRequest.SerializeToString,
            user__code__pb2.LogLikelihoodGradientResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LogPrior(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.health.v1.UserCode/LogPrior',
            user__code__pb2.LogPriorRequest.SerializeToString,
            user__code__pb2.LogPriorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LogPriorGradient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.health.v1.UserCode/LogPriorGradient',
            user__code__pb2.LogPriorGradientRequest.SerializeToString,
            user__code__pb2.LogPriorGradientResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InitialState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.health.v1.UserCode/InitialState',
            user__code__pb2.InitialStateRequest.SerializeToString,
            user__code__pb2.InitialStateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class HealthStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/grpc.health.v1.Health/Check',
                request_serializer=user__code__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=user__code__pb2.HealthCheckResponse.FromString,
                )
        self.Watch = channel.unary_stream(
                '/grpc.health.v1.Health/Watch',
                request_serializer=user__code__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=user__code__pb2.HealthCheckResponse.FromString,
                )


class HealthServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Watch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=user__code__pb2.HealthCheckRequest.FromString,
                    response_serializer=user__code__pb2.HealthCheckResponse.SerializeToString,
            ),
            'Watch': grpc.unary_stream_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=user__code__pb2.HealthCheckRequest.FromString,
                    response_serializer=user__code__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.health.v1.Health', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Health(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.health.v1.Health/Check',
            user__code__pb2.HealthCheckRequest.SerializeToString,
            user__code__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc.health.v1.Health/Watch',
            user__code__pb2.HealthCheckRequest.SerializeToString,
            user__code__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
