
name: resaas CI client (Linux)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install client dependencies
        run: cd app/client && yarn install
      - name: Build client
        run: cd app/client && yarn build
      - name: Check client format
        run: cd app/client && yarn format-check

